plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
    maven { url = 'https://maven.blamejared.com' }
}

neoForge {
    version = project.neo_version
}

dependencies {
    compileOnly project(':guide-lib:common')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
