license="${mod_license}"

issueTrackerURL="https://github.com/ogata-mizuki-99/multiloader-mods/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
description='''
Export structures and place them instantly with 3D hologram preview and rotation. Guide Lib integration for in-game manual (optional).

構造物のエクスポートおよびプレビュー・回転機能付き即時配置を行うMOD。Guide Lib 連携でゲーム内マニュアル対応（任意）。
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="guide_lib"
    type="optional"
    versionRange="[1.0.0-beta.1,)"
    ordering="AFTER"
    side="BOTH"
