license="${mod_license}"

issueTrackerURL="https://github.com/ogata-mizuki-99/multiloader-mods/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
description='''
Temporarily disguise player skins, nametags, and shadows using a spyglass scan.

望遠鏡で他プレイヤーのスキンをスキャンし、見た目（スキン・頭上ネームタグ）や影を動的に偽装するMOD。
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="guide_lib"
    type="optional"
    versionRange="[1.0.0-beta.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="werewolf"
    type="optional"
    versionRange="[1.0.0-beta.1,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="${mod_id}.mixins.json"
